title: Benoit Simard
email: contact@bsimard.com
description:
  fr: Site de Benoit Simard
  en: Benoit's Blog
keyword:
  fr: blog, java, neo4j, graph, benoit, simard
  en: blog, java, neo4j, graph, benoit, simard
url: http://www.bsimard.com
twitter_username: logisima
github_username:  sim51
discuss_shortname: bsimard

me: "Benoit Simard (@logisima)"

contact-me:
  fr: Me contacter
  en: Contact me
follow-me:
  fr: Suivez-moi sur Twitter
  en: Follow-me on Twitter
github-account:
  fr: Mon compte github
  en: My github account
linked-account:
  fr: Mon profile Linked-in
  en: My profile on Linked-in
page-home:
  fr: Accueil
  en: Home
page-blog:
  fr: Blog
  en: Blog
page-me:
  fr: Qui suis-je
  en: About me
last-blog-post:
  fr: Mes derniers billet
  en: My last posts
posts:
  fr: Les billets
  en: Blog posts
find-me-on-web:
  fr: Retrouvez-moi sur le web
  en: Find me on the web
author:
  fr: Author
  en: Auteur
created:
  fr: Créé le
  en: Created at
permalien:
  fr: Permalien
  en: Permalink
keywords:
  fr: Mot-Clefs
  en: Tags
librist:
  fr: Libriste
  en: Librist
librist-desc:
  fr: Je suis un libriste convaincu ! (et même parfois un peu extrémiste)
  en: And sometimes a little extremist on free software ...
kawa:
  fr: Aimant le café
  en: Kawa lover
kawa-desc:
  fr: Le java c'est bien , en abuser ça craint !
  en: Java world is so cool !
webdev:
  fr: Développeur web
  en: Web developer
webdev-desc:
  fr: Développeur et fier de l'être, vive les artisans du web !
  en: Proud to be a developper !
data:
  fr: Et les données
  en: Data addict
data-desc:
  fr: Quelles soient big, linked ou open, j'aime les data !
  en: Big, linked or open, I'm addict to data (specially on graph databases)

destination: docs

############################################################
# Site configuration for the Jekyll 3 Pagination Plugin
# The values here represent the defaults if nothing is set
pagination:
  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 5
############################################################

keep_files: [public/images/diag]
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    imagesdir: /public/images/diag
